version: '3.8'

services:
  php:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
        - ./ms_data:/usr/src/app/cache
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password

volumes:
  db_data:
  ms_data:
